### PR TITLE
Fix/1769 blind checkbox from transfer to box detail

### LINKED ISSUE #1769: Move the blind check box to the box detail

### PR DESCRIPTION
**Pull request by leandroradusky**
Closes #1769 and #1777.

The blind samples checkbox is now in the 'New Box' form and was removed from the transfers.

image

Some comments about the code:
- The `blinded` param was removed from the `TransferPackages` controller and moved into the `Boxes` controller.
- The `BoxForm` build method read the param mentioned above.
- The `TransferPackage` model doesn't have the `attr_accessor :blinded` anymore, this has effects on several tests, where  `make!` was requiring it. New blueprints were created to `make!` transfers of blinded boxes. 
- The `blinded` attribute of the boxes is mandatory, tests creating boxes were modified accordingly to create the boxes with this attribute.
- The test verifying that transferring a box and blinding it was effectively blinding the samples was removed. There is already test for boxes that verify the correct blinding then no new tests were added. 

Functional tests made:
- A box is created unblinded, samples are unblinded for the creator, then is transferred, confirmed and samples remain unblinded for the receiver(#1777 solved!). The automatic blinding was happening.
- A box is created blinded, samples are blinded for the creator, then is transferred and confirmed, samples remain blinded for the receiver, then is unblinded, samples unblind for the receiver.

### CODE REVIEW

**Comment by omelao** [comment]
I could be wrong in what I'm going to say but...the `blinded` field was already in `box model`. In transfers it was like a fake field, just to set it in the boxes. The information in database was always stored on `boxes`.

> A box is created blinded, samples are blinded for the creator, then is transferred and confirmed, samples remain blinded for the receiver, then is unblinded, samples unblind for the receiver.

The question is, how do you unblind this boxes if the sender doesn't see it anymore? Who is unblinding?

**Comment by leandroradusky** [comment]
Hi @omelao ... Within the transfer there is yet the unblind button, which unblinds the boxes. The code doing this is 

```
  def unblind_boxes!
    boxes.update_all(blinded: false)
  end
```

Called by `unblind` method in the `TransferPackagesController`. As long as I tested it was working ok.

**Review by ysbaddaden — APPROVED** [review]
It looks good to me. Permissions aren't an issue until we allow to _edit_ a box. I just left a comment to improve a spec.

Once the conflicts with main are fixed, please merge!

**Comment by omelao** [comment]
These `@floating_transfer` and `@confirmed_transfer` on `box_controller_spec.rb` were created to test the printing buttons on transfers. I think we don't need some specs anymore.  I will check this tomorrow.

**Comment by omelao** [comment]
line 202 - 209 `it "confirmed box should be accessible to sender" do`, we don't need this anymore. The other specs I did are still relevant.

**Review by omelao — COMMENTED** [review]
I don't know how to mention unchanged lines on my review. But you need to remove `box_resource` function from line 26, 38 and the entire function lines 172-183.

**Pull request merged**
