### PR TITLE
Remove client_max_body_size

### PR DESCRIPTION
**Pull request by devduarte**
-Remove client_max_body_size.conf from the repo and from the `dockerfile`

### CODE REVIEW

**Comment by ysbaddaden** [comment]
I'm not sure we want to _remove_ the max body size, it should just be large enough to fit the largest files that must uploaded. Having a 10MB or 20MB limit seems reasonable.

ping @matiasgarciaisaia

**Comment by matiasgarciaisaia** [comment]
We're deleting the limit here so we don't override the runtime-defined limit that we can now set in the base `instedd/nginx-rails` image since instedd/docker-nginx-rails@2771b2a36732877f82c4ff1f6d06a2b18a5dd325.

There's always nginx's default if users don't set a custom one.

**Comment by ysbaddaden** [comment]
Oh sweet!

**Review by matiasgarciaisaia — APPROVED** [review]
👍 🎉

**Pull request merged**
