### PR TITLE
New box form with the option of adding samples from inventory

### LINKED ISSUE #1731: New box form with the option of adding samples from inventory
The new box form should have the following fields:
1. Box ID
2. Purpose
3. Media
4. Samples source.  New field, radio button with 2 options: 1) Create new samples; 2) Select samples from inventory

When the user selects `... from inventory`, we need to show the Content field with the `Add sample` feature.  Today, this is shown when the user picks the "Other" purpose.  

When the user selects `Create new samples` let's do nothing, it's out of the scope of this ticket.

### Acceptance criteria
1. I can select the option `Pick from inventory` and I see the `Add sample` feature appearing.
2. I can add 1 to N samples.
3. I can save the box and see it appearing in the list of boxes.
4. I can transfer the box with all its samples.

### Invision
1. [Select samples from inventory](https://projects.invisionapp.com/d/main#/console/4103589/470301678/preview)
2. [Add samples](https://projects.invisionapp.com/d/main#/console/4103589/470301679/preview)
3. [List of added samples](https://projects.invisionapp.com/d/main#/console/4103589/470301680/preview)

### PR DESCRIPTION
**Pull request by ysbaddaden**
closes #1731

### CODE REVIEW

**Review by ysbaddaden — COMMENTED** [review]
@omelao I think the PR is good. Can you rebase with `main` so you get the official SVG icons, which should fix the merge conflicts? Can you also cleanup all the `console.log` debug?

You might want to look at the failing unit spec on CI, but don't spend more than 15 minutes on it, it's related to box purposes that we'll change anyway.

Then let's wait for the backend to be implemented before merging to `main`. Let's create a `preview/boxes-v2` branch from `main` and merge this PR into it, as well as subsequent ones. Bonus is that CI will still build docker images (as long as tests pass) that can be deployed to staging.

**Comment by leandroradusky** [comment]
Closes #1731 , #1732 & #1733. Closes #1786 as well for free since the form continues to work.

Screenshots in the next comment. Code comments I will add those that I have, the vast majority of the functionality was already working and I've only tested it, maybe Carlos can add further information.

**Comment by leandroradusky** [comment]
Creating a box with new samples:

image

Adding concentrations:

image

**Review by ysbaddaden — COMMENTED** [review]
Good job @omelao @leandroradusky!

A few typos, a suggestion to improve readability, and we're good to go.

**Comment by leandroradusky** [comment]
Hi! 

I've worked on the PR reviews... I'm raising my hand with respect for some usability comments that I have:

Testing if errors are correctly shown, let's suppose I'm creating a Challenge box where, minimally, I need to have a `virus` and a `distractor` batch. If I don't include them, then I'm losing all the uploaded batches/samples/concentrations info and I have to go with `create new samples` from scratch:

image

Also, the fact that I cannot "reopen details" for loaded batches to check if I made a mistake doesn't feel good. In the picture below, all the definitions for batch 12 remain hidden and I cannot see them. Let's suppose that I don't recall if I made it a distractor or not, or, that I forget to make it a distractor and I want to change that: once I press `Add` there is no step back nor to change neither to check... Given that boxes will be quite sophisticated this feels not so good.

image

Last, if I press the "Add button" for this batch:

image

I will lose the 2 replicates of 40 copies/ml since I didn't press the blue check... While it's correct, I'm making this mistake each time I'm creating boxes and, said as above that once you "Add" a batch you can not inspect it, this appears to me as super error prone...

In brief, the component is working well and it respects the mockups but the feeling when using it is that it will lead to creation errors often (detected by the user and forcing to recreate the box, and, worst, undetected until the labels are printed or the inventory is downloaded).

**Comment by diegoliberman** [comment]
@leandroradusky all valid observations.  Please create 1 commit work item for each, in the Candidates increment.  After the feature for uploading the CSV of samples for the box, these work items are the priority.

**Pull request merged**
